version: '3'

services:

  db:
      image: postgres:latest
      volumes:
        - postgres-db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=psql -h localhost -p 5432 -U pz_database_user -d pz_db_test
        - POSTGRES_USER=ahmad
        - POSTGRES_PASSWORD=1234
      ports:
        - "5435:5435"

  app:
    image: ahmaddocker0019/django-sample-app
    ports:
      - "8000:8000"

    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

    # env_file:
    #   - ./.env.dev
    depends_on:
      - db

  # db:
  #   image: postgres:10-alpineALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']
  #   env_file:
  #     - ./.env.dev
  #   volumes: 
  #     - pgdata:/var/lib/postgresql/data
  # redis:
  #   image: redis:alpine
  # celery:
  #   restart: always
  #   build:
  #     context: .
  #   command: celery -A app worker -l info
  #   volumes:
  #     - ./app:/app
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - db
  #     - redis
  #     - app
volumes:
  postgres-db: